# Generated by Django 5.2.8 on 2025-11-18 21:04

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("source_filename", models.CharField(max_length=255)),
                (
                    "original_file",
                    models.FileField(upload_to=api.models.dataset_upload_path),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("total_records", models.PositiveIntegerField()),
                ("avg_flowrate", models.FloatField()),
                ("avg_pressure", models.FloatField()),
                ("avg_temperature", models.FloatField()),
                ("type_distribution", models.JSONField(default=dict)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("records", models.JSONField()),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
